<?php
/**
 * Copyright © OpenGento, All rights reserved.
 * See LICENSE bundled with this library for license details.
 */
declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Opengento\Gdpr\ViewModel\Customer\Privacy\EraseDataProvider;

/** @var Template $block */
/** @var Escaper $escaper */
$escaper = $escaper ?? $block;

/** @var EraseDataProvider $eraseDataProvider */
$eraseDataProvider = $block->getData('eraseDataProvider');
?>
<div class="block block-order-details-view">
    <div class="block-title">
        <strong><?= $escaper->escapeHtml(__('Right to be forgotten')) ?></strong>
    </div>
    <?php if ($eraseDataProvider->getErasureInformationHtml()): ?>
        <div class="block-content">
            <div class="widget block block-static-block">
                <?= $eraseDataProvider->getErasureInformationHtml() ?>
            </div>
        </div>
    <?php endif; ?>
</div>
