<?php
/**
 * Copyright © OpenGento, All rights reserved.
 * See LICENSE bundled with this library for license details.
 */

/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Magento\Framework\Escaper $escaper */

/** @var \Opengento\Gdpr\ViewModel\Customer\Privacy\ExportDataProvider $exportDataProvider */
$exportDataProvider = $block->getData('exportDataProvider');
?>
<div class="block block-order-details-view">
    <div class="block-title">
        <strong><?= $escaper->escapeHtml(__('Export Personal Data')) ?></strong>
    </div>
    <?php if ($exportDataProvider->getExportInformationHtml()): ?>
        <div class="block-content">
            <div class="widget block block-static-block">
                <?= $exportDataProvider->getExportInformationHtml() ?>
            </div>
        </div>
    <?php endif; ?>
</div>
