<?php
/**
 * Copyright © OpenGento, All rights reserved.
 * See LICENSE bundled with this library for license details.
 */
declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Opengento\Gdpr\ViewModel\Customer\Privacy\ExportDataProvider;

/** @var Template $block */
/** @var Escaper $escaper */
$escaper = $escaper ?? $block;

/** @var ExportDataProvider $exportDataProvider */
$exportDataProvider = $block->getData('exportDataProvider');
?>
<div class="block block-order-details-view">
    <div class="block-title">
        <strong><?= $escaper->escapeHtml(__('Export Personal Data')) ?></strong>
    </div>
    <?php if ($exportDataProvider->getExportInformationHtml()): ?>
        <div class="block-content">
            <div class="widget block block-static-block">
                <?= $exportDataProvider->getExportInformationHtml() ?>
            </div>
        </div>
    <?php endif; ?>
</div>
