<?php
/**
 * Copyright © 2018 OpenGento, All rights reserved.
 * See LICENSE bundled with this library for license details.
 */

/** @var \Magento\Framework\View\Element\Template $block */

/** @var \Opengento\Gdpr\ViewModel\Privacy\SettingsDataProvider $settingsDataProvider */
$settingsDataProvider = $block->getData('settingsDataProvider');
/** @var \Opengento\Gdpr\ViewModel\UrlsDataProvider $urlsDataProvider */
$urlsDataProvider = $block->getData('urlsDataProvider');
?>
<form class="form form-edit-account"
      action="<?= $block->escapeUrl($urlsDataProvider->getDeleteActionUrl()) ?>"
      method="post"
      id="form-validate"
      data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
      autocomplete="off"
      novalidate="novalidate">
    <fieldset class="fieldset" data-container="delete-account">
        <?= $block->getBlockHtml('formkey') ?>
        <legend class="legend">
            <span><?= $block->escapeHtml(__('Required Fields')) ?></span>
        </legend>
        <div class="field password current required">
            <label class="label" for="current-password">
                <span><?= $block->escapeHtml(__('Password')) ?></span>
            </label>
            <div class="control">
                <input type="password" class="input-text" name="password" id="password" data-validate="{required:true}" autocomplete="off" />
            </div>
        </div>
        <div class="field reason required">
            <label class="label" for="reason">
                <span><?= $block->escapeHtml(__('Reason')) ?></span>
            </label>
            <div class="control">
                <textarea class="textarea" name="reason" id="reason" data-validate="{required:true}" autocomplete="off"></textarea>
            </div>
            <div class="comment">
                <?= $block->escapeHtml(__('Please explain why you want to erase your account.')) ?>
            </div>
        </div>
        <div class="actions-toolbar">
            <div class="primary">
                <button type="submit" class="button-red action submit primary" id="delete" title="<?= $block->escapeHtmlAttr(__('Delete Account')) ?>">
                    <span><?= $block->escapeHtml(__('Delete Account')) ?></span>
                </button>
            </div>
            <div class="secondary">
                <a class="action back" href="<?= $block->escapeUrl($urlsDataProvider->getSettingsPageUrl()) ?>">
                    <span><?= $block->escapeHtml(__('Back')) ?></span>
                </a>
            </div>
        </div>
    </fieldset>
</form>

<script type="text/javascript">
    require([
        'jquery',
        'Magento_Ui/js/modal/confirm',
        'mage/validation'
    ], function ($, confirm) {
        'use strict';

        var dataForm = $('#form-validate'),
            ignore = null;

        dataForm
            .mage('validation', {
                ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
            })
            .find('input:text')
            .attr('autocomplete', 'off');

        $('#delete').on({
            click: function () {
                if (dataForm.validation('isValid')) {
                    confirm({
                        title: $.mage.__('Attention'),
                        content: $.mage.__('Do you really want to delete your account?'),
                        actions: {
                            confirm: function () {
                                dataForm.submit();
                            },
                            cancel: function () {},
                            always: function () {}
                        }
                    })
                }
            }
        });
    });
</script>
