<?php
/**
 * Copyright © 2018 OpenGento, All rights reserved.
 * See LICENSE bundled with this library for license details.
 */

use Opengento\Gdpr\Helper\Data;

/** @var \Opengento\Gdpr\Block\Account\Delete $block */
/** @var Data $helper */
$helper = $this->helper(Data::class);
?>
<form class="form form-edit-account"
      action="<?= $block->escapeUrl($block->getUrl('privacy/delete/delete')) ?>"
      method="post"
      id="form-validate"
      data-hasrequired="<?= $block->escapeHtml(__('* Required Fields')) ?>"
      autocomplete="off">
    <fieldset class="fieldset" data-container="delete-account">
        <?= $block->getBlockHtml('formkey') ?>
        <legend class="legend">
            <span><?= __('Required data') ?></span>
        </legend>
        <div class="field password current required">
            <label class="label" for="current-password">
                <span><?= __('Password') ?></span>
            </label>
            <div class="control">
                <input type="password" class="input-text" name="password" id="password" data-validate="{required:true}" autocomplete="off"/>
            </div>
        </div>

        <div class="field reason required">
            <label class="label" for="current-password">
                <span><?= __('Reason'); ?></span>
            </label>
            <div class="control">
                <textarea class="textarea" name="reason" id="reason" data-validate="{required:true}" autocomplete="off"></textarea>
            </div>
            <div class="comment">
                <?= $block->escapeHtml($helper->getDeletionReasonInfo()) ?>
            </div>
        </div>

        <div class="actions-toolbar">
            <div class="primary">
                <button type="button" class="button-red action submit primary" id="delete">
                    <span><?= __('Delete my account') ?></span>
                </button>
            </div>
            <div class="secondary">
                <a class="action" href="<?= $block->escapeUrl($block->getSettingsUrl()) ?>">
                    <span><?= __('Go back') ?></span>
                </a>
            </div>
        </div>
    </fieldset>
</form>


<script type="text/javascript">
    require([
        'jquery',
        'Magento_Ui/js/modal/confirm',
        'mage/validation'
    ], function ($, confirm) {
        'use strict';

        var dataForm = $('#form-validate'),
            ignore = null;

        dataForm
            .mage('validation', {
                ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
            })
            .find('input:text')
            .attr('autocomplete', 'off');

        $('#delete').on({
            click: function () {
                if (dataForm.validation('isValid')) {
                    confirm({
                        title: $.mage.__('Attention'),
                        content: $.mage.__('Do you really want to delete your account?'),
                        actions: {
                            confirm: function () {
                                dataForm.submit();
                            },
                            cancel: function () {},
                            always: function () {}
                        }
                    })
                }
            }
        });
    });
</script>
