<?php
/**
 * Copyright © OpenGento, All rights reserved.
 * See LICENSE bundled with this library for license details.
 */

/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Magento\Framework\Escaper $escaper */

/** @var \Opengento\Gdpr\ViewModel\Customer\Privacy\SettingsDataProvider $settingsDataProvider */
$settingsDataProvider = $block->getData('settingsDataProvider');
?>
<?php if ($settingsDataProvider->getPrivacyInformationHtml()): ?>
    <div class="block block-dashboard-info">
        <div class="block-title">
            <strong><?= $escaper->escapeHtml(__('Information')) ?></strong>
        </div>
        <div class="block-content">
            <div class="widget block block-static-block">
                <?= $settingsDataProvider->getPrivacyInformationHtml() ?>
            </div>
        </div>
    </div>
<?php endif; ?>
<div class="block block-privacy-info">
    <?= $block->getChildHtml() ?>
</div>
