<?php
/**
 * Copyright © OpenGento, All rights reserved.
 * See LICENSE bundled with this library for license details.
 */

/** @var \Magento\Framework\View\Element\Template $block */

/** @var \Magento\Framework\View\Element\RendererList $rendererList */
$rendererList = $block->getChildBlock('exportRenderer');

/** @var \Magento\Framework\DataObject $viewModel */
$viewModel = $block->getData('viewModel');
?>
<?php foreach ($viewModel->toArray() as $key => $value): ?>
    <div class="fieldset info export-data-<?= $block->escapeHtmlAttr($key) ?>">
        <div class="legend"><span><?= $block->escapeHtml($key) ?></span></div>
        <div class="field field-<?= $block->escapeHtmlAttr($key) ?>">
            <?php if (is_array($value)): ?>
                <pre>
                    <?= print_r($value, true) ?>
                </pre>
            <?php elseif ($value): ?>
                <p><?= $block->escapeHtml($value) ?></p>
            <?php endif; ?>
        </div>
    </div>
<?php endforeach; ?>
