<?php
/**
 * Copyright © OpenGento, All rights reserved.
 * See LICENSE bundled with this library for license details.
 */

/** @var \Magento\Framework\View\Element\Template $block */

/** @var \Opengento\Gdpr\ViewModel\Privacy\ErasureDataProvider $erasureDataProvider */
$erasureDataProvider = $block->getData('erasureDataProvider');
/** @var \Opengento\Gdpr\ViewModel\UrlsDataProvider $urlsDataProvider */
$urlsDataProvider = $block->getData('urlsDataProvider');
?>
<div class="block block-dashboard-info">
    <div class="block-title">
        <strong><?= $block->escapeHtml(__('Right to be forgotten')) ?></strong>
    </div>
    <div class="block-content">
        <div class="widget block block-static-block">
            <?= $erasureDataProvider->getErasureInformation() ?>
        </div>
        <?php if ($erasureDataProvider->canBeCanceled()): ?>
            <div class="message warning">
                <span><?= $block->escapeHtml(__('Your account will be deleted soon. You can undo this action.')) ?></span>
            </div>
            <div class="actions-toolbar">
                <div class="primary">
                    <a href="<?= $block->escapeUrl($urlsDataProvider->getUndoDeleteActionUrl()) ?>" class="action submit primary" id="undo_deletion">
                        <span><?= $block->escapeHtml(__('Undo Action')) ?></span>
                    </a>
                </div>
            </div>
        <?php elseif ($erasureDataProvider->canBeProcessed()): ?>
            <div class="widget block block-static-block">
                <?= $erasureDataProvider->getAnonymizeInformation() ?>
            </div>
            <div class="actions-toolbar">
                <div class="primary">
                    <a href="<?= $block->escapeUrl($urlsDataProvider->getDeletePageUrl()) ?>" class="action submit primary primary-danger" id="delete">
                        <span><?= $block->escapeHtml(__('Delete Account')) ?></span>
                    </a>
                </div>
            </div>
        <?php endif; ?>
    </div>
</div>
