<?php
/**
 * Copyright © OpenGento, All rights reserved.
 * See LICENSE bundled with this library for license details.
 */

/** @var \Magento\Framework\View\Element\Template $block */

/** @var \Opengento\Gdpr\ViewModel\Privacy\ExportDataProvider $exportDataProvider */
$exportDataProvider = $block->getData('exportDataProvider');
/** @var \Opengento\Gdpr\ViewModel\Privacy\ExportCustomerDataProvider $exportCustomerDataProvider */
$exportCustomerDataProvider = $block->getData('exportCustomerDataProvider');
/** @var \Opengento\Gdpr\ViewModel\UrlsDataProvider $urlsDataProvider */
$urlsDataProvider = $block->getData('urlsDataProvider');
?>
<div class="block block-dashboard-info">
    <div class="block-title">
        <strong><?= $block->escapeHtml(__('Export Personal Data')) ?></strong>
    </div>
    <div class="block-content">
        <div class="widget block block-static-block">
            <?= $exportDataProvider->getExportInformationHtml() ?>
        </div>
        <div class="actions-toolbar">
            <div class="primary">
                <?php if ($exportCustomerDataProvider->isExported()): ?>
                    <a href="<?= $block->escapeUrl($urlsDataProvider->getDownloadActionUrl()) ?>" class="action submit primary" id="download">
                        <span><?= $block->escapeHtml(__('Download Personal Data')) ?></span>
                    </a>
                <?php elseif ($exportCustomerDataProvider->hasExport()): ?>
                    <div class="message info">
                        <span><?= $block->escapeHtml(__('Your personal data document is pending export.')) ?></span>
                    </div>
                <?php else: ?>
                    <a href="<?= $block->escapeUrl($urlsDataProvider->getExportActionUrl()) ?>" class="action submit primary" id="export">
                        <span><?= $block->escapeHtml(__('Export Personal Data')) ?></span>
                    </a>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>
