<?php
/**
 * Copyright © OpenGento, All rights reserved.
 * See LICENSE bundled with this library for license details.
 */
/** @var \Opengento\Gdpr\Block\Messages\PrivacyMessagePopup $block */
?>
<div class="enhanced-privacy-cookie-policy" data-type="cookie-policy" data-bind="scope: 'enhanced-privacy-cookie-policy'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
<script type="text/x-magento-init">
    {
        "[data-type='cookie-policy']": {
            "Magento_Ui/js/core/app": <?= $block->getJsLayout() ?>
        }
    }
</script>
