<?php
/**
 * Copyright © OpenGento, All rights reserved.
 * See LICENSE bundled with this library for license details.
 */

/** @var \Magento\Framework\View\Element\Template $block */

/** @var \Opengento\Gdpr\ViewModel\Privacy\ExportCustomerDataProvider $exportCustomerDataProvider */
$exportCustomerDataProvider = $block->getData('exportCustomerDataProvider');
?>
<?php if ($exportCustomerDataProvider->isExported()): ?>
    <a href="<?= $block->escapeHtmlAttr($block->escapeUrl($block->getData('actionUrl'))) ?>" class="action export">
        <span><?= $block->escapeHtml(__('Download Personal Data')) ?></span>
    </a>
<?php elseif ($exportCustomerDataProvider->hasExport()): ?>
    <div class="message info">
        <span><?= $block->escapeHtml(__('Your personal data document is pending export.')) ?></span>
    </div>
<?php endif; ?>
