<?php
/**
 * Copyright © OpenGento, All rights reserved.
 * See LICENSE bundled with this library for license details.
 */

/** @var \Magento\Framework\View\Element\Template $block */

/** @var \Opengento\Gdpr\ViewModel\Customer\Guest\EraseDataProvider $eraseDataProvider */
$eraseDataProvider = $block->getData('eraseDataProvider');
?>
<?php if ($eraseDataProvider->canCreate()): ?>
    <a href="<?= $block->escapeUrl($block->getData('eraseActionUrl')) ?>" class="action action-danger" id="erase">
        <span><?= $block->escapeHtml(__('Erase Personal Data')) ?></span>
    </a>
    <script>
        require([
            "jquery",
            "Magento_Ui/js/modal/confirm"
        ], function ($, confirm) {
            'use strict';

            $("#erase").on("click", function (e) {
                e.preventDefault();
                confirm({
                    title: "<?= $block->escapeJs($block->escapeHtml(__('Warning'))) ?>",
                    content: "<?= $block->escapeJs($block->escapeHtml(__('Do you really want to erase your personal data?'))) ?>",
                    actions: {
                        confirm: function () {
                            window.location = "<?= $block->escapeJs($block->escapeUrl($block->getData('eraseActionUrl'))) ?>";
                        }
                    }
                });
            });
        });
    </script>
<?php endif; ?>
<?php if ($eraseDataProvider->canCancel()): ?>
    <a href="<?= $block->escapeUrl($block->getData('undoActionUrl')) ?>" class="action undo" id="undo_deletion">
        <span><?= $block->escapeHtml(__('Undo Erase Personal Data')) ?></span>
    </a>
<?php endif; ?>
