<?php
/**
 * Copyright © OpenGento, All rights reserved.
 * See LICENSE bundled with this library for license details.
 */

/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Magento\Framework\Escaper $escaper */

/** @var \Opengento\Gdpr\ViewModel\Customer\Guest\ExportDataProvider $exportDataProvider */
$exportDataProvider = $block->getData('exportDataProvider');
?>
<?php if (!$exportDataProvider->hasExport()): ?>
    <a href="<?= $escaper->escapeHtmlAttr($escaper->escapeUrl($block->getData('actionUrl'))) ?>" class="action export">
        <span><?= $escaper->escapeHtml(__('Export Personal Data')) ?></span>
    </a>
<?php endif; ?>
