name: M2 PHPStan
on: [push, pull_request, workflow_dispatch]

jobs:
  phpstan:
    name: M2 PHPStan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: extdn/github-actions-m2/magento-phpstan/8.2@master
        with:
          composer_name: opengento/module-gdpr
